name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile.prod --tag ${{ secrets.DOCKER_USERNAME }}/pbs-bahamas-state-backend:latest

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pbs-bahamas-state-backend:latest
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd deploy-state-website/
            chmod +x ./rebuild-containers.sh
            sudo ./rebuild-containers.sh
